#!/usr/bin/env python3
"""Launch ArUco pickup alignment followed by pose correction."""

import os

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def default_robot_namespace():
    return {
        "1": "tb3_0",
        "2": "tb3_1",
        "3": "tb3_2",
    }.get(os.environ.get("USER", "")[-1:], "")


def scoped_topic(namespace, name):
    return f"/{namespace}/{name}" if namespace else f"/{name}"


def scoped_frame(namespace, name):
    return f"{namespace}/{name}" if namespace else name


def generate_launch_description():
    robot_namespace = default_robot_namespace()
    default_marker_map = PathJoinSubstitution([
        FindPackageShare("logitle_aruco_tools"),
        "config",
        "logitle_marker_map.yaml",
    ])

    return LaunchDescription([
        DeclareLaunchArgument("image_topic", default_value="/camera/image_raw"),
        DeclareLaunchArgument("camera_info_topic", default_value="/camera/camera_info"),
        DeclareLaunchArgument("dictionary", default_value="5X5_1000"),
        DeclareLaunchArgument("marker_id", default_value="25"),
        DeclareLaunchArgument("marker_size", default_value="0.04"),
        DeclareLaunchArgument("marker_map", default_value=default_marker_map),
        DeclareLaunchArgument(
            "pose_topic_template",
            default_value=scoped_topic(robot_namespace, "aruco/id{marker_id}/pose_camera"),
        ),
        DeclareLaunchArgument("pose_frame_id", default_value="camera_optical_frame"),
        DeclareLaunchArgument("align_action_name", default_value=scoped_topic(robot_namespace, "aruco_align_and_correct")),
        DeclareLaunchArgument("correct_action_name", default_value=scoped_topic(robot_namespace, "aruco_correct_pose")),
        DeclareLaunchArgument("cmd_vel_topic", default_value="/cmd_vel"),
        DeclareLaunchArgument("cmd_vel_stamped", default_value="true"),
        DeclareLaunchArgument("cmd_frame_id", default_value="base_footprint"),
        DeclareLaunchArgument("map_frame", default_value="map"),
        DeclareLaunchArgument("odom_frame", default_value="odom"),
        DeclareLaunchArgument("base_frame", default_value="base_footprint"),
        DeclareLaunchArgument("initialpose_topic", default_value="/initialpose"),
        DeclareLaunchArgument("target_x", default_value="-0.173"),
        DeclareLaunchArgument("target_z", default_value="0.392"),
        DeclareLaunchArgument("x_tolerance", default_value="0.005"),
        DeclareLaunchArgument("z_tolerance", default_value="0.007"),
        DeclareLaunchArgument("z_min_stop", default_value="0.25"),
        DeclareLaunchArgument("stable_sec", default_value="0.4"),
        DeclareLaunchArgument("max_linear", default_value="0.030"),
        DeclareLaunchArgument("max_angular", default_value="0.12"),
        DeclareLaunchArgument("kx", default_value="2.5"),
        DeclareLaunchArgument("wall_yaw_tolerance_deg", default_value="1.0"),
        DeclareLaunchArgument("kz", default_value="1.2"),
        DeclareLaunchArgument("kyaw", default_value="1.2"),
        DeclareLaunchArgument("align_timeout_sec", default_value="25.0"),
        DeclareLaunchArgument("correct_timeout_sec", default_value="10.0"),
        DeclareLaunchArgument("required_samples", default_value="15"),
        DeclareLaunchArgument("yaw_tolerance_deg", default_value="3.0"),
        DeclareLaunchArgument("camera_x", default_value="0.045"),
        DeclareLaunchArgument("camera_y", default_value="0.0"),
        DeclareLaunchArgument("camera_z", default_value="0.115"),
        DeclareLaunchArgument("camera_pitch", default_value="-5.0"),
        DeclareLaunchArgument("camera_yaw", default_value="0.0"),
        DeclareLaunchArgument("camera_roll", default_value="0.0"),
        DeclareLaunchArgument("pose_source", default_value="camera"),
        DeclareLaunchArgument("approx_camera_info", default_value="false"),
        DeclareLaunchArgument("approx_horizontal_fov_deg", default_value="62.2"),
        Node(
            package="logitle_aruco_tools",
            executable="logitle_aruco_pose_corrector_action_server",
            name="aruco_pose_corrector_action_server",
            namespace=robot_namespace,
            output="screen",
            arguments=[
                "--action-name",
                LaunchConfiguration("correct_action_name"),
                "--pose-source",
                LaunchConfiguration("pose_source"),
                "--image-topic",
                LaunchConfiguration("image_topic"),
                "--camera-info-topic",
                LaunchConfiguration("camera_info_topic"),
                "--dictionary",
                LaunchConfiguration("dictionary"),
                "--pose-topic-template",
                LaunchConfiguration("pose_topic_template"),
                "--pose-frame-id",
                LaunchConfiguration("pose_frame_id"),
                "--marker-id",
                LaunchConfiguration("marker_id"),
                "--marker-size",
                LaunchConfiguration("marker_size"),
                "--marker-map",
                LaunchConfiguration("marker_map"),
                "--camera-x",
                LaunchConfiguration("camera_x"),
                "--camera-y",
                LaunchConfiguration("camera_y"),
                "--camera-z",
                LaunchConfiguration("camera_z"),
                "--camera-pitch",
                LaunchConfiguration("camera_pitch"),
                "--camera-yaw",
                LaunchConfiguration("camera_yaw"),
                "--camera-roll",
                LaunchConfiguration("camera_roll"),
                "--approx-camera-info",
                LaunchConfiguration("approx_camera_info"),
                "--approx-horizontal-fov-deg",
                LaunchConfiguration("approx_horizontal_fov_deg"),
                "--map-frame",
                LaunchConfiguration("map_frame"),
                "--odom-frame",
                LaunchConfiguration("odom_frame"),
                "--base-frame",
                LaunchConfiguration("base_frame"),
                "--initialpose-topic",
                LaunchConfiguration("initialpose_topic"),
            ],
        ),
        Node(
            package="logitle_aruco_tools",
            executable="logitle_align_and_correct_action_server",
            name="align_and_correct_with_aruco_action_server",
            namespace=robot_namespace,
            output="screen",
            arguments=[
                "--action-name",
                LaunchConfiguration("align_action_name"),
                "--correct-action-name",
                LaunchConfiguration("correct_action_name"),
                "--pose-source",
                LaunchConfiguration("pose_source"),
                "--image-topic",
                LaunchConfiguration("image_topic"),
                "--camera-info-topic",
                LaunchConfiguration("camera_info_topic"),
                "--dictionary",
                LaunchConfiguration("dictionary"),
                "--pose-topic-template",
                LaunchConfiguration("pose_topic_template"),
                "--pose-frame-id",
                LaunchConfiguration("pose_frame_id"),
                "--marker-map",
                LaunchConfiguration("marker_map"),
                "--marker-id",
                LaunchConfiguration("marker_id"),
                "--marker-size",
                LaunchConfiguration("marker_size"),
                "--cmd-vel-topic",
                LaunchConfiguration("cmd_vel_topic"),
                "--cmd-vel-stamped",
                LaunchConfiguration("cmd_vel_stamped"),
                "--cmd-frame-id",
                LaunchConfiguration("cmd_frame_id"),
                "--target-z",
                LaunchConfiguration("target_z"),
                "--target-x",
                LaunchConfiguration("target_x"),
                "--x-tolerance",
                LaunchConfiguration("x_tolerance"),
                "--z-tolerance",
                LaunchConfiguration("z_tolerance"),
                "--z-min-stop",
                LaunchConfiguration("z_min_stop"),
                "--stable-sec",
                LaunchConfiguration("stable_sec"),
                "--max-linear",
                LaunchConfiguration("max_linear"),
                "--max-angular",
                LaunchConfiguration("max_angular"),
                "--kx",
                LaunchConfiguration("kx"),
                "--kz",
                LaunchConfiguration("kz"),
                "--wall-yaw-tolerance-deg",
                LaunchConfiguration("wall_yaw_tolerance_deg"),
                "--kyaw",
                LaunchConfiguration("kyaw"),
                "--align-timeout-sec",
                LaunchConfiguration("align_timeout_sec"),
                "--correct-timeout-sec",
                LaunchConfiguration("correct_timeout_sec"),
                "--required-samples",
                LaunchConfiguration("required_samples"),
                "--yaw-tolerance-deg",
                LaunchConfiguration("yaw_tolerance_deg"),
                "--approx-camera-info",
                LaunchConfiguration("approx_camera_info"),
                "--approx-horizontal-fov-deg",
                LaunchConfiguration("approx_horizontal_fov_deg"),
            ],
        ),
    ])
