#!/usr/bin/env python3
"""Launch ArUco pickup alignment followed by pose correction."""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    default_marker_map = PathJoinSubstitution([
        FindPackageShare("logitle_aruco_tools"),
        "config",
        "logitle_marker_map.yaml",
    ])

    return LaunchDescription([
        DeclareLaunchArgument("image_topic", default_value="/camera/image_raw"),
        DeclareLaunchArgument("camera_info_topic", default_value="/camera/camera_info"),
        DeclareLaunchArgument("dictionary", default_value="5X5_50"),
        DeclareLaunchArgument("marker_id", default_value="24"),
        DeclareLaunchArgument("marker_size", default_value="0.0395"),
        DeclareLaunchArgument("marker_map", default_value=default_marker_map),
        DeclareLaunchArgument("pose_topic_template", default_value="/aruco/id{marker_id}/pose_camera"),
        DeclareLaunchArgument("align_action_name", default_value="/aruco_align_and_correct"),
        DeclareLaunchArgument("correct_action_name", default_value="/aruco_correct_pose"),
        DeclareLaunchArgument("cmd_vel_topic", default_value="/cmd_vel"),
        DeclareLaunchArgument("cmd_vel_stamped", default_value="true"),
        DeclareLaunchArgument("target_z", default_value="0.32"),
        DeclareLaunchArgument("x_tolerance", default_value="0.025"),
        DeclareLaunchArgument("z_tolerance", default_value="0.035"),
        DeclareLaunchArgument("z_min_stop", default_value="0.25"),
        DeclareLaunchArgument("stable_sec", default_value="0.5"),
        DeclareLaunchArgument("max_linear", default_value="0.015"),
        DeclareLaunchArgument("max_angular", default_value="0.08"),
        DeclareLaunchArgument("align_timeout_sec", default_value="10.0"),
        DeclareLaunchArgument("correct_timeout_sec", default_value="10.0"),
        DeclareLaunchArgument("required_samples", default_value="15"),
        DeclareLaunchArgument("yaw_tolerance_deg", default_value="4.0"),
        DeclareLaunchArgument("camera_x", default_value="0.045"),
        DeclareLaunchArgument("camera_y", default_value="0.0"),
        DeclareLaunchArgument("camera_z", default_value="0.115"),
        DeclareLaunchArgument("camera_pitch", default_value="-5.0"),
        DeclareLaunchArgument("camera_yaw", default_value="0.0"),
        DeclareLaunchArgument("camera_roll", default_value="0.0"),
        Node(
            package="logitle_aruco_tools",
            executable="logitle_aruco_pose_viewer",
            name="aruco_pose_viewer",
            output="screen",
            arguments=[
                "--no-gui",
                "--image-topic",
                LaunchConfiguration("image_topic"),
                "--camera-info-topic",
                LaunchConfiguration("camera_info_topic"),
                "--dictionary",
                LaunchConfiguration("dictionary"),
                "--marker-id",
                LaunchConfiguration("marker_id"),
                "--marker-size",
                LaunchConfiguration("marker_size"),
                "--marker-map",
                LaunchConfiguration("marker_map"),
            ],
        ),
        Node(
            package="logitle_aruco_tools",
            executable="logitle_aruco_pose_corrector_action_server",
            name="aruco_pose_corrector_action_server",
            output="screen",
            arguments=[
                "--action-name",
                LaunchConfiguration("correct_action_name"),
                "--pose-source",
                "topic",
                "--pose-topic-template",
                LaunchConfiguration("pose_topic_template"),
                "--marker-id",
                LaunchConfiguration("marker_id"),
                "--marker-size",
                LaunchConfiguration("marker_size"),
                "--marker-map",
                LaunchConfiguration("marker_map"),
                "--camera-x",
                LaunchConfiguration("camera_x"),
                "--camera-y",
                LaunchConfiguration("camera_y"),
                "--camera-z",
                LaunchConfiguration("camera_z"),
                "--camera-pitch",
                LaunchConfiguration("camera_pitch"),
                "--camera-yaw",
                LaunchConfiguration("camera_yaw"),
                "--camera-roll",
                LaunchConfiguration("camera_roll"),
            ],
        ),
        Node(
            package="logitle_aruco_tools",
            executable="logitle_align_and_correct_action_server",
            name="align_and_correct_with_aruco_action_server",
            output="screen",
            arguments=[
                "--action-name",
                LaunchConfiguration("align_action_name"),
                "--correct-action-name",
                LaunchConfiguration("correct_action_name"),
                "--pose-topic-template",
                LaunchConfiguration("pose_topic_template"),
                "--marker-id",
                LaunchConfiguration("marker_id"),
                "--cmd-vel-topic",
                LaunchConfiguration("cmd_vel_topic"),
                "--cmd-vel-stamped",
                LaunchConfiguration("cmd_vel_stamped"),
                "--target-z",
                LaunchConfiguration("target_z"),
                "--x-tolerance",
                LaunchConfiguration("x_tolerance"),
                "--z-tolerance",
                LaunchConfiguration("z_tolerance"),
                "--z-min-stop",
                LaunchConfiguration("z_min_stop"),
                "--stable-sec",
                LaunchConfiguration("stable_sec"),
                "--max-linear",
                LaunchConfiguration("max_linear"),
                "--max-angular",
                LaunchConfiguration("max_angular"),
                "--align-timeout-sec",
                LaunchConfiguration("align_timeout_sec"),
                "--correct-timeout-sec",
                LaunchConfiguration("correct_timeout_sec"),
                "--required-samples",
                LaunchConfiguration("required_samples"),
                "--yaw-tolerance-deg",
                LaunchConfiguration("yaw_tolerance_deg"),
            ],
        ),
    ])
